image: registry.gitlab.com/ondraknow/chess:latest

before_script:
  - echo "richard"
stages:
  - testing
  - build-package


testy:
  stage: testing
  script:
  - echo "test"

build:
  stage: build-package
  script:
  - cmake -H. -BBuild
  - /usr/bin/cmake --build /builds/OndraKnow/chess/Build --config Debug --target all -- -j 6
  artifacts:
    paths:
      - /builds/OndraKnow/chess/Build

